name: reform
description: >-
  Pure dart form validation and sanitization,
  built with Flutter in mind
repository: https://github.com/AlexanderFarkas/reform/tree/main/packages/reform

version: 0.3.0

environment:
  sdk: '>=2.17.0 <3.0.0'